### ISSUE TITLE
Should develop be protected

### ISSUE THREAD

**Issue by andrewgazelka** [Team-2502/RobotCode2019#15]
I think we should PR into `develop` for non-trivial additions. Should we also be forced to PR? I am indifferent.

**Comment by ryandalex1** [comment]
I agree that we should PR for non-trivial additions but not be forced to in the case of quick changes for testing on robot like changing the speed of autos

**Comment by andrewgazelka** [comment]
I agree with you @ryandalex1 . Probably the best idea is to just publicly shame people who don't use PR's for giant changes. :p
