### ISSUE TITLE
Should we use a fish-eye lens camera?

### ISSUE THREAD

**Issue by andrewgazelka** [Team-2502/RobotCode2019#3]

**Comment by andrewgazelka** [comment]
**Michael Wagner**
> You also can’t use the wireless functionalities of a go pro on the field.
> I also believe you can’t output video over the USB port and you would need a hdmi to usb adapter

**Comment by andrewgazelka** [comment]
We can use them if we disable wireless functionalities. Teams have used them before I think... although there is probably a much better camera for live view. Changing the title to 
> should we have a fish-eye lens camera

https://www.reddit.com/r/FRC/comments/7te5hc/can_i_use_a_gopro/
https://www.reddit.com/r/FRC/comments/2rixei/is_there_any_way_to_take_a_webcam_or_a_gopro_then/

**Comment by andrewgazelka** [comment]
Also if we have a fish-eye lens do you think we would want to use this for the first 15 seconds driver aid _along with_ our computer vision systems?

**Comment by ritikmishra** [comment]
closed because we bought a camera
