### ISSUE TITLE
Make NavX a part of DriveTrainSubsystem?

### ISSUE THREAD

**Issue by ritikmishra** [Team-2502/RobotCode2019#8]
The only subsystem that would use the NavX for anything would be the DriveTrainSubsystem. After all, the NavX is used heavily for odometry/localization, which pertain almost exclusively to the DriveTrain.

**Comment by isaacaj** [comment]
Closed because we no longer use the NAVX which needs to be a robot object, and instead use the PigeonIMU board which is a part of the DriveTrainSubsystem.
